# Quality Demo

We demo 3 different functions for collecting revision quality measures from Wikipedia:
1. `get_revisions_quality` - for getting quality scores for a list of revision IDs.
2. `get_articles_quality` - for getting quality scores for a list of titles / page IDs.
3. `pipeline_quality` - A convenience wrapper function that, in addition to the above, also sets up session and redirect maps.

All of these functions are able to access models through the Wikimedia lift wing API (including the older revscoring/ORES models). These models are:
- `articlequality` - language agnostic revision quality score 0-1
- `revertrisk-multilingual` - multilingual revision revert risk probability 0-1
- `revertrisk-language-agnostic` - language agnostic revision revert risk probability 0-1
- `{wiki}-articlequality` - ORES revision quality - probability of Start/Stub/C/B/GA/FA 0-1
- `{wiki}-draftquality` - ORES draft quality - probability of OK/attack/spam/vandalism 0-1
- `{wiki}-goodfaith` - ORES "good faith" revision probability 0-1
- `{wiki}-damaging` - ORES "damaging" revision probability 0-1
- `{wiki}-reverted` - ORES revision reverted probability 0-1

## Setup

In [1]:
import wikitoolkit
import pandas as pd

my_agent = 'mwapi testing <p.gildersleve@exeter.ac.uk>'
wtsession = wikitoolkit.WTSession('en.wikipedia', user_agent=my_agent)

pagemaps = wikitoolkit.PageMaps() # see demo_redirects.ipynb for more info

toparts = pd.read_csv('data/topviews-2024_07_31.csv')
artlist = toparts['Page'].unique().tolist() # ~1000 top articles yesterday
revision_ids = [1236428488,
                1236453299,
                1237461948,
                1237046423,
                1237232495,
                1236992079,
                1236436502,
                1236488217,
                1236305118,
                1237376589] # 10 random revision ids

## `get_revisions_quality`

Gets quality scores based on revision IDs.

In [2]:
# articlequality is the default model
r_quality = await wikitoolkit.get_revisions_quality(wtsession, revision_ids, 'en')
pd.DataFrame(r_quality).T

Querying 10 revisions with model articlequality, attempt 1

            articlequality
1236428488        0.852792
1236453299        0.852699
1237461948        0.954037
1237046423        0.954933
1237232495        0.954475
1236992079        0.955253
1236436502        0.852638
1236488217        0.981080
1236305118        0.986865
1237376589        0.361192

Can handle other models:

In [3]:
r_quality = await wikitoolkit.get_revisions_quality(wtsession, revision_ids, 'en', models=['articlequality', "revertrisk-multilingual"])
pd.DataFrame(r_quality).T

Querying 10 revisions with model articlequality, attempt 1
Querying 10 revisions with model revertrisk-multilingual, attempt 1

            articlequality  revertrisk-multilingual
1236428488        0.852792                 0.837449
1236453299        0.852699                 0.277937
1237461948        0.954037                 0.188958
1237046423        0.954933                 0.185478
1237232495        0.954475                 0.040484
1236992079        0.955253                 0.280694
1236436502        0.852638                 0.705815
1236488217        0.981080                 0.244512
1236305118        0.986865                 0.644111
1237376589        0.361192                 0.138911

## `get_articles_quality`

Gets quality scores based on article titles or page IDs. Gets most recent revision by default, but can get revision at date, or revisions in range.

In [4]:
a_quality = await wikitoolkit.get_articles_quality(wtsession, titles=artlist[:10],
                           lang='en', pagemaps=pagemaps)
pd.DataFrame(a_quality).T

Querying 10 revisions with model articlequality, attempt 1

,revid,parentid,timestamp,articlequality
2024 Summer Olympics,1266501529,1266380204,2024-12-31T23:24:42Z,0.98258
Simone Biles,1264516827,1261685269,2024-12-22T07:40:18Z,0.981833
Deadpool & Wolverine,1266552346,1266513364,2025-01-01T04:36:54Z,0.962009
Sunisa Lee,1263625812,1263435227,2024-12-17T19:17:03Z,0.988088
Katie Ledecky,1266338437,1263327473,2024-12-31T04:23:03Z,0.990766
Michael Phelps,1266495180,1266016456,2024-12-31T22:37:14Z,0.995521
Ismail Haniyeh,1263516011,1261633776,2024-12-17T02:51:20Z,0.710398
Jonathan Owens,1266172647,1248830926,2024-12-30T12:02:39Z,0.395941
MyKayla Skinner,1262993291,1256054504,2024-12-14T02:05:45Z,0.755887
Kamala Harris,1266507143,1266337989,2025-01-01T00:01:48Z,1.0

In [5]:
a_quality = await wikitoolkit.get_articles_quality(wtsession, titles=artlist[:10],
                           start='2015-07-31T00:00:00Z', stop='2015-08-07T00:00:00Z', 
                           lang='en', pagemaps=pagemaps)
pd.concat({k: pd.DataFrame(v) for k, v in a_quality.items()}
          ).reset_index(level=1, drop=True).reset_index().rename(columns={'index': 'title'})

Querying 97 revisions with model articlequality, attempt 1

,title,revid,parentid,timestamp,articlequality
0,2024 Summer Olympics,673884162.0,673833579.0,2015-07-31T04:26:40Z,0.317917
1,2024 Summer Olympics,673902932.0,673884162.0,2015-07-31T08:06:23Z,0.317917
2,2024 Summer Olympics,673934466.0,673902932.0,2015-07-31T13:36:29Z,0.317917
3,2024 Summer Olympics,673960667.0,673934466.0,2015-07-31T17:17:58Z,0.317917
4,2024 Summer Olympics,673995596.0,673960667.0,2015-07-31T22:03:39Z,0.321032
...,...,...,...,...,...
92,Katie Ledecky,674861758.0,674831322.0,2015-08-06T16:41:50Z,0.723786
93,Katie Ledecky,674873571.0,674861758.0,2015-08-06T18:10:42Z,0.723786
94,Katie Ledecky,674900561.0,674873571.0,2015-08-06T21:49:54Z,0.724138
95,MyKayla Skinner,674183591.0,673825992.0,2015-08-02T06:33:34Z,0.466670
96,Kamala Harris,674784612.0,673028346.0,2015-08-06T03:30:17Z,0.875018

## `pipeline_quality`

This function sets up the session, fixes redirects with PageMaps (if necessary), and collects revision quality data. It is a convenience function that wraps the previous functions to collect by revision ID / title / page ID. Different models / dates / date ranges can still be specified. Note that this does not require manual setup of the `wtsession`.

In [6]:
p_quality = await wikitoolkit.pipeline_quality('en.wikipedia', my_agent,
                                               titles=artlist[:10], pagemaps=pagemaps)
pd.DataFrame(p_quality).T

Querying 10 revisions with model articlequality, attempt 1

,revid,parentid,timestamp,articlequality
2024 Summer Olympics,1266501529,1266380204,2024-12-31T23:24:42Z,0.98258
Simone Biles,1264516827,1261685269,2024-12-22T07:40:18Z,0.981833
Deadpool & Wolverine,1266552346,1266513364,2025-01-01T04:36:54Z,0.962009
Sunisa Lee,1263625812,1263435227,2024-12-17T19:17:03Z,0.988088
Katie Ledecky,1266338437,1263327473,2024-12-31T04:23:03Z,0.990766
Michael Phelps,1266495180,1266016456,2024-12-31T22:37:14Z,0.995521
Ismail Haniyeh,1263516011,1261633776,2024-12-17T02:51:20Z,0.710398
Jonathan Owens,1266172647,1248830926,2024-12-30T12:02:39Z,0.395941
MyKayla Skinner,1262993291,1256054504,2024-12-14T02:05:45Z,0.755887
Kamala Harris,1266507143,1266337989,2025-01-01T00:01:48Z,1.0

In [3]:
p_quality = await wikitoolkit.pipeline_quality('en.wikipedia', my_agent, titles=artlist[:10],
                                               qf_args={'start': '2024-10-20T01:59:14Z', 'stop': '2024-10-23T01:59:14Z'},
                                               models=['articlequality', 'revertrisk-multilingual'],
                                               pagemaps=pagemaps)
pd.concat({k: pd.DataFrame(v) for k, v in p_quality.items()}
          ).reset_index(level=1, drop=True).reset_index().rename(columns={'index': 'title'})

Querying 29 revisions with model articlequality, attempt 1
22 revisions failed with 504. Retrying in 1 seconds...
Querying 22 revisions with model articlequality, attempt 2
22 revisions failed with 504. Retrying in 2 seconds...
Querying 22 revisions with model articlequality, attempt 3
22 revisions failed with 504. Retrying in 4 seconds...
Querying 22 revisions with model articlequality, attempt 4
20 revisions failed with 504. Retrying in 8 seconds...
Querying 20 revisions with model articlequality, attempt 5
5 revisions failed with 504. Retrying in 16 seconds...
Failed to get quality scores for 5 revisions after 5 attempts
Querying 29 revisions with model revertrisk-multilingual, attempt 1
3 revisions failed with 504. Retrying in 1 seconds...
Querying 3 revisions with model revertrisk-multilingual, attempt 2
1 revisions failed with 504. Retrying in 2 seconds...
Querying 1 revisions with model revertrisk-multilingual, attempt 3
1 revisions failed with 504. Retrying in 4 seconds...
Querying 1 revisions with model revertrisk-multilingual, attempt 4
1 revisions failed with 504. Retrying in 8 seconds...
Querying 1 revisions with model revertrisk-multilingual, attempt 5
1 revisions failed with 504. Retrying in 16 seconds...
Failed to get quality scores for 1 revisions after 5 attempts

,title,revid,parentid,timestamp,revertrisk-multilingual,articlequality
0,Sunisa Lee,1.252390e+09,1.246513e+09,2024-10-21T03:44:40Z,-1.000000,NaN
1,Sunisa Lee,1.252392e+09,1.252390e+09,2024-10-21T03:58:19Z,0.596069,0.988588
2,Sunisa Lee,1.252803e+09,1.252392e+09,2024-10-23T00:44:55Z,0.824312,0.988588
3,Sunisa Lee,1.252803e+09,1.252803e+09,2024-10-23T00:45:26Z,0.525482,0.988588
4,2024 Summer Olympics,1.252797e+09,1.251789e+09,2024-10-23T00:06:57Z,0.505047,0.982580
5,Kamala Harris,1.252222e+09,1.252127e+09,2024-10-20T11:21:59Z,0.204967,0.997366
6,Kamala Harris,1.252595e+09,1.252222e+09,2024-10-22T01:48:56Z,0.205229,0.997360
7,Kamala Harris,1.252681e+09,1.252595e+09,2024-10-22T14:01:16Z,0.356726,0.997360
8,Kamala Harris,1.252751e+09,1.252681e+09,2024-10-22T20:04:08Z,0.083439,0.997366
9,Deadpool & Wolverine,1.252228e+09,1.252100e+09,2024-10-20T12:03:34Z,0.203159,0.960395
10,Deadpool & Wolverine,1.252325e+09,1.252228e+09,2024-10-20T21:09:00Z,0.189760,0.960395
11,Deadpool & Wolverine,1.252404e+09,1.252325e+09,2024-10-21T05:42:48Z,0.273872,0.960395
12,Deadpool & Wolverine,1.252404e+09,1.252404e+09,2024-10-21T05:43:27Z,0.393080,0.960395
13,Deadpool & Wolverine,1.252579e+09,1.252404e+09,2024-10-22T00:10:29Z,0.442908,0.960392
14,Deadpool & Wolverine,1.252581e+09,1.252579e+09,2024-10-22T00:19:18Z,0.234179,-1.000000
15,Deadpool & Wolverine,1.252614e+09,1.252581e+09,2024-10-22T04:37:52Z,0.160781,0.960404
16,Deadpool & Wolverine,1.252658e+09,1.252614e+09,2024-10-22T11:14:07Z,0.124154,0.960395
17,Deadpool & Wolverine,1.252680e+09,1.252658e+09,2024-10-22T13:55:35Z,0.208601,0.960458
18,Deadpool & Wolverine,1.252766e+09,1.252680e+09,2024-10-22T21:16:05Z,0.189623,0.960442
19,Deadpool & Wolverine,1.252768e+09,1.252766e+09,2024-10-22T21:26:38Z,0.306056,-1.000000
20,Ismail Haniyeh,1.252229e+09,1.252101e+09,2024-10-20T12:12:47Z,0.101060,0.710482
21,Ismail Haniyeh,1.252372e+09,1.252229e+09,2024-10-21T01:34:04Z,0.337414,0.710482
22,Ismail Haniyeh,1.252419e+09,1.252372e+09,2024-10-21T07:43:50Z,0.241985,0.710482
23,Ismail Haniyeh,1.252439e+09,1.252419e+09,2024-10-21T10:37:08Z,0.259377,-1.000000
24,Ismail Haniyeh,1.252442e+09,1.252439e+09,2024-10-21T11:00:57Z,0.293192,-1.000000
25,Ismail Haniyeh,1.252445e+09,1.252442e+09,2024-10-21T11:28:30Z,0.319005,-1.000000
26,Ismail Haniyeh,1.252451e+09,1.252445e+09,2024-10-21T12:11:21Z,0.245523,0.710482
27,Ismail Haniyeh,1.252500e+09,1.252451e+09,2024-10-21T16:48:17Z,0.246041,0.710482
28,Ismail Haniyeh,1.252624e+09,1.252500e+09,2024-10-22T06:15:18Z,0.342238,0.710366